
---
- hosts: all
  gather_facts: false
  connection: local

# get provider id from API endpoint
  vars:
    provider_id: "1"
    max_retries: 9
    retry_interval: 20

  tasks:
#    - debug: var=vcenter_hostname
#    - debug: var=esxi_host
#    - debug: var=datacenter
#    - debug: var=template
#    - debug: var=vm_hostname
#    - debug: var=manageiq.api_url
#    - debug: var=manageiq.api_token
#    - debug: var=manageiq.service
#    - debug: var=ansible_default_ipv4.address
    - debug: var=ram
    - debug: var=vcpu

    - set_fact: ram2=8192
    
    - debug: var=ram
    
    
    - name: Set the Provider URL
      set_fact:
        provider_url: "{{ manageiq.api_url }}/api/providers/{{ provider_id }}"

    - name: Set the Service URL
      set_fact:
        svc_url: "/api/{{ manageiq.service }}"

        #    - name: Gather the facts for the template
        #      vmware_vm_facts:
        #        validate_certs: no
        #        hostname: "{{ vcenter_hostname }}"
        #        name: "{{ template }}"
        #      register: new_vm
        #
        #    - debug: var=new_vm    
#    - debug: var=svc_url 

# get definition of vsphere module : https://docs.ansible.com/ansible/latest/modules/vsphere_guest_module.html
    - name: Create Virtual Machines
      vmware_guest:
        validate_certs: no
        hostname: "{{ vcenter_hostname }}"
        datacenter: "{{ datacenter }}"
        name: "{{ vm_hostname }}"
        template: "{{ template }}"
        state: poweredon
        cluster: "{{ vmware_cluster }}"
        folder: "{{ folder }}"
        hardware:
          memory_mb: "{{ ram }}"
          num_cpus: "{{ vcpu }}"
          hotadd: True
        wait_for_ip_address: False

        #   - name: Update Virtual Machines
        #     vmware_guest:
        #       validate_certs: no
        #       vcenter_hostname: "{{ vcenter_hostname }}"
        #       guest: "{{ vm_hostname }}"
        #       state: reconfigured
        #       vm_extra_config:
        #         vcpu.hotadd: yes
        #         mem.hotadd:  yes
        #       vm_hardware:
        #         memory_mb: "{{ ram | int }}"
        #         num_cpus: "{{ vcpu | int }}"

    - name: Gather the facts for the VM
      vmware_vm_facts:
        validate_certs: no
        hostname: "{{ vcenter_hostname }}"
        vm_type: vm
      register: all_vms

    - debug: var=all_vms.virtual_machines[vm_hostname].uuid    

      #    - debug:
      #        msg: "{{ item.uuid }}"
      #      with_items:
      #        - "{{ all_vms.virtual_machines | json_query(query) }}"
      #      vars:
      #        query: "[?guest_name=='a']"
      #    
    - set_fact: new_vm_uuid="{{ all_vms.virtual_machines[vm_hostname].uuid }}"
      #      with_items:
      #        - "{{ all_vms.virtual_machines | json_query(query) }}"
      #      vars:
      #        query: "[?guest_name=={{ vm_hostname }}]"

    - debug: var=new_vm_uuid

    - name: Refresh provider in CloudForms
      uri:
        url: "{{ provider_url }}"
        method: POST
        body:
          action: refresh
        body_format: json
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json" 
        status_code: 200
      register: output

#    - debug: var=output

    - name: set the task href
      set_fact:
        task_url: "{{ output.json.task_href}}"

#    - debug: var=task_url

    - name: Wait for the refresh to end
      uri:
        url: "{{ task_url }}"
        method: GET
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json" 
        status_code: 200
      register: task_result
      until: task_result.json.state == 'Finished' or task_result.json.status == 'Error'
      failed_when: task_result.json.status == 'Error'
      retries: "{{max_retries}}"
      delay: "{{retry_interval}}"

#    - debug: var=task_result
    
    - set_fact: find_vm_url="{{ manageiq.api_url }}/api/vms?expand=resources&attributes=href,uid_ems&filter[]=uid_ems='{{ new_vm_uuid }}'"

#    - debug: var=find_vm_url

    - name: Call to CloudForms to find href for new_vm_uuid
      uri:
        url: "{{ find_vm_url }}"
        method: GET
        validate_certs: no
        headers:
           X-Auth-Token: "{{ manageiq.api_token }}"
           Content-Type: "application/json"
        body_format: json
        return_content: yes
      register: token_output

#    - debug: var=token_output

    - set_fact: cf_vm_href="{{ token_output.json.resources[0].href }}"

#    - debug: var=cf_vm_href

    - name: Create an array of vms
      set_fact:
        vms: "{{ vms|default([]) + [ { 'href': svc_url, 'resource':  { 'href': item } } ] }}"
      with_items:
        - "{{ cf_vm_href }}"

#    - debug: var=vms
    
    - name: Register vm with the service
      uri:
        url: "{{ manageiq.api_url }}/api/services"
        method: POST
        body_format: json
        body:
          action: add_resource
          resources : "{{ vms }}"
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json"
        status_code: 200
      register: output

    - set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d\\ %H:%M') }}"

    - name: Get the existing service name
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: GET
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
        body_format: json
      register: current_service

    - name: Update the service name with appended timestamp
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
        body_format: json
        body:
          action: edit
          resource:
            name: "{{ current_service.json.name }} {{ timestamp }}"  


    - name: Get the existing service name
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: GET
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
        body_format: json
      register: current_service  

    - debug: var=current_service
    
#    - debug: var=output.json.results[0].success

