---
- hosts: all
  gather_facts: false
  connection: local

# get provider id from API endpoint
  vars:
    provider_id: "1"
    max_retries: 9
    retry_interval: 20

  tasks:
    - debug: var=vcenter_hostname
    - debug: var=vm_hostname

    # - set_fact:
    #     timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d\\ %H:%M') }}"

    # - name: Get the existing service name
    #   uri:
    #     url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
    #     method: GET
    #     validate_certs: no
    #     headers:
    #       X-Auth-Token: "{{ manageiq.api_token }}"
    #     body_format: json
    #   register: current_service

    # - name: Update the service name with appended timestamp
    #   uri:
    #     url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
    #     method: POST
    #     validate_certs: no
    #     headers:
    #       X-Auth-Token: "{{ manageiq.api_token }}"
    #     body_format: json
    #     body:
    #       action: edit
    #       resource:
    #         name: "{{ current_service.json.name }} {{ timestamp }}"    

    # - name: Set the Provider URL
    #   set_fact:
    #     provider_url: "{{ manageiq.api_url }}/api/providers/{{ provider_id }}"

    # - name: Set the Service URL
    #   set_fact:
    #     svc_url: "/api/{{ manageiq.service }}"

    # - name: Remove VM
    #   vmware_guest:
    #     validate_certs: False      
    #     hostname: "{{ vcenter_hostname }}"
    #     name: "{{ vm_hostname }}"
    #     state: absent
