---
- hosts: all
  gather_facts: false
  connection: local

# get provider id from API endpoint
  vars:
    provider_id: "1"
    max_retries: 9
    retry_interval: 20

  tasks:
    - name: Remove VM
      vmware_guest:
        validate_certs: False      
        hostname: "{{ vcenter_hostname }}"
        name: "{{ vm_hostname }}"
        state: absent
