---
- hosts: localhost

  tasks:
    - name: Remove VM
      vmware_guest:
        validate_certs: False      
        hostname: "{{ vcenter_hostname }}"
        name: "{{ vm_hostname }}"
        state: absent
