---
- hosts: all
  gather_facts: false
  connection: local

# get provider id from API endpoint
  vars:
    provider_id: "1"
    max_retries: 9
    retry_interval: 20

  tasks:
    - debug: var=vcenter_hostname
    - debug: var=vm_hostname

    
    - name: Get the existing service name
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: GET
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
        body_format: json
      register: current_service  

    - debug: var=current_service

    - name: Set the Provider URL
      set_fact:
        provider_url: "{{ manageiq.api_url }}/api/providers/{{ provider_id }}"

    - name: Set the Service URL
      set_fact:
        svc_url: "/api/{{ manageiq.service }}"

    - set_fact: vcenter_hostname="{{ current_servicejson.options.dialog.dialog_param_vcenter_hostname }}"
    - set_fact: vm_hostname="{{ current_service.json.options.dialog.dialog_param_vm_hostname }}"

    - name: Remove VM
      vmware_guest:
        validate_certs: False      
        hostname: "{{ vcenter_hostname }}"
        name: "{{ vm_hostname }}"
        state: absent
